stream_command.go
=> use jsm metadata partser not nats.go

go.mod, go.sum, nats/consumer_command.go, nats/pub_command.go, nats/reply_command.go, nats/sub_command.go, nats/util.go
Pub and Reply can both do templates in their body
now, the same was added to header values.
Unique IDs can be generated using {{.ID}}
=> Add text templating to more strings

nats/server_mkpasswd_command.go, nats/stream_command.go
=> improve rendering of mkpasswd ui in some setups

nats/server_report_command.go
We tried to show a shorter version of the account id for the
long key based ones, but didn't account for static account names
that can be shorter
=> Only shorten long account names

nats/stream_command.go
applies to mirror/source. fixes #192
=> [fixed] crash by omitting check when no subject is present

nats/server_report_command.go, nats/server_request_command.go, nats/util.go
When no waitFor is specified use a combination of overall timeout
and a sliding window of 300ms for responses to scatter and gather
requests.
If no results are received for 300ms the comment assumes it's done
this is only active when waitFor==0
=> use a sliding window for waiting for responses

nats/bench_command.go
Adds the following flags to the 'bench' command, introduces JS support and new request/reply mode
example uses:
benchmark core nats publish and subscribe with 10 publishers and subscribers
```
nats bench testsubject --pub 10 --sub 10 --msgs 10000 --size 512
```
benchmark core nats request/reply with queuing
```
nats bench testsubject --sub 4 --reply 
nats bench testsubject --pub 4 --request --msgs 20000
```
benchmark JetStream acknowledged publishes
```
nats bench testsubject --js --syncpub --pub 10  --msgs 10000
```
benchmark JS publish and push consumers at the same time
```
nats bench testsubject --pub 4 --sub 4 --js
```
benchmark just publishing into a JS stream, do not delete the stream so the data in it can be reused by another benchmark (like below)
```
nats bench testsubject --pub …
```
=> Adds streaming and request/reply to the bench functionality

nats/bench_command.go, nats/util.go
Added --pubtimeout to control the timeout for JS asynch publishing and changed the default to a more sane 30s. Re-worked and improved progress bars, which now work for subscribing as well as publishing.
=> Added --pubtimeout to control the timeout for JS asynch publishing

nats/bench_command.go
nats connect needs url,natsOpts()... in order for the connection with –tlsca and –creds to work (was mistakenly removed by some earlier commit thinking it was un-needed)
=> fix nats connect call

cli/server_list_command.go, cli/util.go
CLI sub-command "server list" reported nonsensical "negative uptimes" in
a number of situations. Generally, this is due to calculating Uptime based
on the CLI's wall-clock and comparing with the UTC timestamp in
'statsz.start'.
Previously Uptime was essentially 'time.Since(statsz.start)', which
compares CLI's local wall clock with the UTC timestamp in statsz.start.
This is brittle, it requires clocks be synchronized on the CLI and on
NATS Server.
A "better" approximation of NATS Server Uptime is the duration between
'server.time' and 'statsz.start'. The time domain error is scoped to a
single machine's estimation of UTC when:
1. NATS Server most recently started
2. "this" statsz was rendered by the server in "1"
This is not robust against wall clock resets.
To the best of my knowledge, …
=> Calculate "Uptime" monotonically in sub-command "server list"

cli/server_check_command.go, cli/server_check_command_test.go
CLI sub-command "server check server" reported nonsensical "negative uptimes" in
a number of situations. Generally, this is due to calculating Uptime based
on the CLI's wall-clock and comparing with the UTC timestamp in
'varz.start'.
Previously Uptime was essentially 'time.Since(varz.start)', which
compares CLI's local wall clock with the UTC timestamp in varsz.start.
This is brittle, it requires clocks be synchronized on the CLI and on
NATS Server.
A "better" approximation of NATS Server Uptime is the duration between
'server.time' and 'varsz.start'. The time domain error is scoped to a
single machine's estimation of UTC when:
1. NATS Server most recently started
2. "this" varsz was rendered by the server in "1"
This is not robust against wall clock resets.
varz does have a 'uptime' …
=> Use "varz Uptime" in sub-command "server check server"

.goreleaser.yml
The change to go mod compatible version changes
required a update to the versioning definitions
but this somehow skipped being comitted
=> add uncommitted changes

cli/cli.go, cli/context_command.go, cli/pub_command.go, cli/reply_command.go, cli/util.go, go.mod, go.sum, nats/main.go
--count limits the number of messages to reply to before exiting
--reply allows to specify the reply subject
fixes #314
requesting with a different subject (instead of a plain inbox) is a pattern nats allows for. 
Which is why natscli should support it natively, just to make demos easier.
When I experimented with this, the go api, always overwrote the reply subject with an inbox.
Which is why code to avoid the request was added too.
=> adding --count to reply and --reply to request

cli/stream_command.go
Add trailing newline in user output
=> cli/stream_command.go: add trailing newline

README.md
Fixed usage of code block showing a shell command being executed and it's output, such that people can simply copy and paste those commands in their own shells without having to then remove the `$ ` prompt at the start of the line. Used 'Output' as a separator, but open to better ideas.
=> Fixed usage of code blocks to facilitate copy and paste of the commands

cli/object_command.go
I´ve seen that there is no way to remove a ObjectStore with natscli so added a Function, Commands and Action like it is handled in `kv_command.go `
**BUT**: `rm` (and `del`) was used different to the `kv` command:
in kv context `rm` removes the bucket and `del` deletes the key. 
With this patch I also align this to the `object` command: `rm` removes the ObejectStore und `del` deletes a object.
Maybe some docs need to be updated too.
If this change ist considered wrong I can rework this merge request....
=> add rmAction to call DeleteObjectStore

cli/server_check_command.go
It is not possible to check these connections are up at present and
longer term we are looking to make the connections dynamic
meaning it would be even harder to make basic assertions like
this that are meaningful.
So removing these 2 sets of checks for now
=> remove route and gateway connection assertions

README.md, cli/context_command.go, cli/errors_command.go, cli/kv_command.go, cli/schema_command.go, cli/schema_info_command.go, cli/server_list_command.go
Closes #336 
Includes the following changes:
- Use on info vs show
- Use on ls vs list
- Fix minor spelling issue on schema
Commands changed from `show` to `info` were aliased to maintain backward compatibility.
=> Rename commands for consistency

README.md
* JetStream was GA as of server v2.2.0
Signed-off-by: Ben Werthmann <ben@synadia.com>
=> docs: Update README with current JetStream status

cli/bench_command.go
New flags: --push (for using a push consumer), --consumerbatch (replaces --pullbatch as it's now used for both push and pull consumers), --kv
=> Adds durable push consumer and initial KV benchmark mode

cli/util.go
nats --context /some/file.json will use that file if accessible
else use the existing behavior.
=> support loading contexts from a filename

cli/consumer_command.go
Using `consumer add` command it is possible to specify `--max-pending` flag.
This PR enables the same but for `consumer edit` flow. Currently, `consumer edit` command doesn't allow to change `max-pending` property of JS Consumer.
=> Add max-pending flag for 'consumer edit' command

cli/pub_command.go
Adds a publish request wait to allow for multiple responses from a publish call.  Updated to honor the timeout for the first message, then wait a `reply-timeout` for subsequent messages, a suggestion by @derekcollison for better UX.
`--replies 0` will gather responses until the global timeout is reached.
```text
nats reply foo "response from service a" --queue a &
nats reply foo "response from service b" --queue b &
nats reply foo "response from service c" --queue c &
```
Publish and wait (edited)
```
$ nats req foo hello
11:15:03 Sending request on "foo"
11:15:03 Received on "_INBOX.Wu6eONq021mLlGG5nWuMGp.SqEPt48b" rtt 406.868µs
response from service a
$ nats req --replies 2 foo hello
11:15:03 Sending request on "foo"
11:15:03 Received on "_INBOX.qf0sz6O8QzaQR3hp2NEfIC.AQNxkIEZ" rtt …
```
=> Add publish request support for multiple responses

cli/stream_command.go
This ensures the placement isnt changed during
update when no changes were requested to tags
=> fix editing streams with tag placement

cli/kv_command.go, cli/object_command.go, cli/stream_command.go, cli/util.go, cli/util_test.go
This uses a bytes parser derived from, and compatible with,
the server options parser but additionally supports TB, tb and
t as aliases for T. All are 1024 based.
We use that in cli arguments and update all other bytes
parsing to be the same, this means 1GB is consistent with
the rendering of 1GiB - all 1024 based.
Do the same on stream, kv and object.
Fixes a bug that required a size be set on accounts
that do not require it and default to 256MB when it is
required
=> Humanize byte arguments on the cli and prompts

cli/stream_command.go
=> avoid printing names stream names list twice

cli/account_command.go
avoiding ui bar altogether (as suggested in https://github.com/nats-io/natscli/pull/448)
=> [fixed] close on closed channel by avoiding ui bar on acc restore

cli/server_run_command.go
=> fix #486 - config.StoreSir path escaping on `server run` for windows OS

cli/sub_command.go
"Chris" on nats slack reported that `nats sub $subject --count $N` did not work with `--raw`; analysis of code exposed that this also does not work with `--raw`.
Adjust the control flow in the registered handler function to treat the pretty-case as another branch, before final clean-up; I rejected the "duplicate the limit check in two other places" approach as not scaling if more work needs to be done on each branch.
=> Honor sub count limits for raw/dump

cli/account_command.go, go.mod, go.sum
These will now be treated as warnings since there is nothing that a user
can do about them - we do not support skipping certain streams etc.
So they will now log, and then report in a seperate section for warnings
and not cause a 1 exit code.
However they can be treated as critical using --critical-warnings
=> handle memory streams better in account backup

LOCAL_DEVELOPMENT.md, cli/server_run_command.go
The behavior of always cleaning contexts after each
run and creating new random passwords and ports on
each start was too difficult to use, especially given
the lack of natscontext support in any other languages.
Now when the required contexts exist the passwords and
port is read from them and reused.  Cleaning behavior
can be enabled with --clean
=> Rework nats server run

cli/stream_command.go
Fixes #529
This PR fixes a typo in the assignment of our interactive prompts in `nats stream add`. The "Allow message deletion" prompt was incorrectly assigning to `c.denyPurge` instead of `c.denyDelete`.
=> fix: deny-delete in interactive prompts overriding deny-purge

cli/consumer_command.go, cli/stream_command.go
For stream and consumer cluster step-down, check for empty leader before proceeding with step-down command.  
In a case where there is no current leader (not a happy path case albeit), the CLI message is mis-formatted under this condition, e.g. `Requesting leader step down of "" in a 4 peer RAFT group
nats: error: JetStream system temporarily unavailable (10008), try --help`  (where it's actually an R3).
=> Check for empty Leader

README.md, cli/sub_command.go
This adds a `--match-replies` flag to `nats sub` which matches replies to any request sent to the subscribed subject.
The feature is implemented using an additional subscription on `_INBOX.>` subject, and a map matching reply subjects to requests.
=> Match replies to request in `nats sub`

cli/stream_command.go, cli/sub_command.go, cli/util.go
Wiretapping is a popular pattern also in the phase of developing/debugging an application. In that case, we create NATS  subscription to include all subjects and can preview which messages are published on NATS by various application producers.
Sometimes there are too noisy subjects (e.g. pings, heartbeats, alive messages) that frequently produce NATS messages and prevent us from seeing core/useful communication when we have a wiretap subscription.
Provide the way to use wiretap subscription and ignore 'noisy' subjects. So we want to be subscribed to all subjects, but we also want to exclude a few of them just to remove noisy traffic.
Expand `sub` command with `--ignore-subject` flag. Within the flag it is possible to specify:
- One or many subjects
- Subject literal, single or multiple …
=> Feature: Ignored Subjects for Sub Command

cli/object_command.go
This is a suggested fix for issue #593 
I decided to rename the flag to `--no-progress` to match the one in the `bench` command
=> Fix progress bars not working

cli/sub_command.go
This PR adds subject filtering back to the `nats sub` command when
`--stream` is specified. Currently whenever `--stream` is specified we
pass "" as the subject, which I don't think was intended functionality,
as it doesn't filter the stream consumer by the subject and also breaks
things like `--last-per-subject`.
Looking at f379dd226d6034dc951994a683465faa74e59ce0 it wasn't clear to
me why we would pass "" as the subject to support this use case.
@ripienaar feel free to add flavor if this fix does in fact break
introduced in that commit.
=> Add back filter subject to nats sub when --stream is specified

cli/stream_command.go
For instance, a discard "new" policy was displayed as:
```
Discard Policy: NewNew
```
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
=> [FIXED] Discard Policy was incorrectly displayed.

cli/kv_command.go
At the moment with limited support for just
a name and a optional domain while the usage patterns become clearer
=> support kv mirrors

cli/consumer_command.go, cli/stream_command.go
Found a typo in the Consumer state. `Acknowledgment` -> `Acknowledgement`.
=> Make `Acknowledgment` spelling consistent

cli/account_command.go, cli/account_tls_command.go
Running `nats server tls` will report all the valid TLS chains verified by the client for the current TLS connection.  Each chain shows the PEM-encoded form of each cert in the chain, preceded by some hopefully-useful data as comments.
We'll warn, and exit with an error, if we're within 1 week of the expiration of a certificate.  This is adjustable with a flag.  Exiting if a cert has expired is not adjustable (but shouldn't happen with verified chains).
There's logic for OCSP verification, taken from my smtpdane tool (I'm the copyright holder of that tool so this is fine, relicensing this copied 20 line snippet as part of natscli).
*Warning*: I'm unable to get OCSP stapling working with a server in my setup, so I haven't been able to properly test the OCSP output mode.  The tool of mine I …
=> New sub-command: account tls

cli/account_tls_command.go
My fault; my code I cribbed from was doing end-of-message newlines
automatically, and I missed the \n when switching to `fmt.Printf()`.  I just
today got an OCSP setup "working" at home, to see the message:
=> OCSP status: fix missing newlines

cli/server_request_command.go, go.mod, go.sum
This adds support for `nats server request profile`, as per the new `PROFILEZ` endpoint in nats-io/nats-server#3774. The profiles are written to files in the supplied directory, so that they can be used with `go tool pprof`.
Signed-off-by: Neil Twigg <neil@nats.io>
=> Add support for `nats server request profile`

cli/context_command.go
Since the `cli` launches an external editor validation of the updated context cannot be done until after it has already been saved to disk. The result is when you enter bad data (e.g. invalid `nsc` path) it will get persisted before the cli notifies you of the error. If you then try to run the edit command again it will fail due to validation checks failing when attempting to load the now bad context. The only solution is to manually edit the context `.json` file on disk.
This PR will check for errors when loading the context after the editor command has returned. If the context fails to validate it will attempt to save the known clean context so that the `nats edit context` command will run in the future. It then returns the error to let the user know what part of the updated context …
=> Rollback context if edit invalid

cli/server_run_command.go
As a follow up to #732 
- Reuse the new escape filter for .StoreDir instead of separate fix.
- Quote store_dir value
=> quote StoreDir and reuse new escape filter

README.md
I updated line 194 so that it can be copied to the terminal.
for the output of the first command line - nats sub --match-replies cli.demo, I am getting the below, so not the same as stated.  And I am having trouble following the rest of this section. (base) marthapena@Marthas-MacBook-Pro ~ % nats sub --match-replies cli.demo 10:15:57 Matching replies with inbox prefix _INBOX.> 10:15:57 Subscribing on cli.demo
=> Issues with following Match requests and replies section

cli/util.go
Propagate the timeout command line flag to wait time value of JetStream client.
We need this change in order to be able to perform the delete from ObjectStore because now this wait time is set by default to 5s and we are not able to modify it from the command line.
=> Propagate timeout from the CLI flags to the JetStream client

cli/cheats/sub.md, cli/sub_command.go
This handy feature (similar to `nats traffic`) builds a table of active subjects currently receiving data. Great for troubleshooting and exploration.
Better than running `nats sub ">"`!
=> Added `nats sub {{pattern}} --report-subjects`

README.md, cli/filter_data_through_cmd.go, cli/stream_command.go, cli/sub_command.go, dependencies.md, go.mod, go.sum
We have decided to use the nats-cli tool to assist in debugging and monitoring NATS stream messages stored in cbor format. However, we would prefer the messages displayed in an easier-to-read formatting. The same goes for JSON, which we would like to have a better readable representation too.
In response to my inquiry #636 about adding an encoder/decoder, @ripienaar suggested that this could be achieved by passing the output through a CLI utility that performs the translation. This would allow users to add their own translators or formatters as needed.
I have created a proof of concept implementation for this approach, and I hope that it will be incorporated into the tool in the future.
I added a template for `{{subject}}` which can be used to let the translator know about the subject, so …
=> Adding the possibility to translate the msg.Data before output.

cli/pub_command.go
While continuing our [AvroX](https://github.com/metatexx/avrox) development, we tripped over the missing --translation for `nats req` so I added it.
=> I forgot to add the translate feature to the req command.

cli/consumer_command.go
Fixes specifying a subject filter through `askOne` when creating a consumer
=> Fix consumer add

cli/kv_command.go
This PR adds the sequence number of a message to the output of `nats kv get <bucket> <key> --trace`
The timestamp of the message was already present but I missed the sequence number. 
I'm aware that the history command shows this information but for me this is the right place as well for this information.
=> add revision to kv get trace output

cli/stream_command.go
This allows the user to edit the desired compression algorithm on a stream.
Signed-off-by: Neil Twigg <neil@nats.io>
=> Allow editing compression on a stream

cli/reply_command.go
I noticed that sometimes the nats CLI process would exit before the reply command response was sent; this resolves that issue.
=> Add a connection flush before interrupting

cli/stream_command.go
Most of  stream help messages ending with "Settable using" does not have dot (.) after the option to use.
Some have, this tailing dot is not practical when copy and paste.
=> Remove dot at end of "Settable using" help.

cli/server_report_command.go
Today reverse sort in report conns is default, this means passing -R is a noop and people need to figure out to pass --no-reverse.
It is less confusing if we make it so -R does the right thing and make that bool unnegatable
=> improve reverse sorting UX

cli/kv_command.go
Fixed typo in confirmation question for ```nats kv del bucketname```: Delete~~d~~ bucket bucketname?
=> fixed typo in confirmation question

cli/kv_command.go
The server defaults to `>`, so only the dest is required.
=> Remove check for repub source

cli/server_report_command.go
When one server is much busier, the "API Err" cell might look uncommonly high,
but the actual error rate is not higher.  Having an "Err %" column should make
that much clearer.
=> server report js: add an "Err %" column

cli/bench_command.go, cli/util.go
Use the global JS settings in calls to `nc.JetStream()` inside of the bench comand
=> use global JS settings in bench command

cli/server_check_command.go, go.mod, go.sum
We had this for backward compatability but it ended up making discoverability of new features impossible.
This introduce a breaking change, but, significantly improves UX
=> Remove the default command for "nats server check"

cli/rtt_command.go
When executing RTT command for NATS cluster setup, RTT is probably not reported correctly for all servers within the cluster.
E.g. after the following command is executed:
```
n rtt -s tls://connect.ngs.global
tls://connect.ngs.global:
tls://34.159.142.0:4222: 15.005017ms
tls://34.89.235.191:4222: 13.955248ms
tls://34.107.15.96:4222: 14.124726ms
```
each RTT reported above was measured for `tls://connect.ngs.global` host (which can be resolved to any IP above) and not for each specific IP listed above. So the report is misleading: it is correct for at least one IP, but probably not for all 3 of them.
This PR fixes that issue.
=> Bug: Fix RTT report when multiple servers are included

cli/rtt_command.go
RTT command examines the final result with few iterations (default is 5).
It should be handy to be able to see RTT for each iteration, and for that purpose `--trace` switch is reused. This PR adds that logic.
Example:
```
nats rtt --trace 8  
RTT iterations for server: nats://127.0.0.1:4222
#1:	rtt=1.514372ms
#2:	rtt=1.924859ms
#3:	rtt=1.322852ms
#4:	rtt=1.31299ms
#5:	rtt=1.120805ms
#6:	rtt=1.121725ms
#7:	rtt=1.133196ms
#8:	rtt=1.321921ms
nats://127.0.0.1:4222:
127.0.0.1: 1.34659ms
```
=> Feature: RTT command verbose mode

cli/tables.go
This would change a micro sign into MS which is not desirable
=> Prevent upper casing all footer content

cli/consumer_command.go
Added to `consumer add`: when prompting for subject filter(s) can parse the user input as a comma or space separated list of subject filters.
=> [ADDED] `consumer add` when prompting for subject filter(s) can parse the user input as a comma or space separated list of subject filters

cli/consumer_command.go
Fixes consumer edit going from 1 subject filter to more than one that would move the filters to the `FilterSubjects` array, but not remove the initial single filter from FilterSubject.
=> [FIXED] consumer edit going from 1 subject filter to more than one

README.md, cli/context_command.go, go.mod, go.sum
New nats context subcommand that allows `cd -` or `git checkout -` type of operation but for NATS context.
This PR implements the logic for switching to the previous (old) nats context using:
- `nats ctx previous`
- `nats ctx -- -` (unfortunately wasn't able to make `nats ctx -` to work)
Example:
```
$ nats ctx select local-sys                                                                                                                                       
NATS Configuration Context "local-sys"
Description: localhost sys
Server URLs: nats://127.0.0.1:4222
Username: admin
Password: ********
Path: /Users/boris/.config/nats/context/local-sys.json
$ nats ctx -- - …
```
=> Feature: Context's command for switching to previous (old) nats context

cli/auth_command.go, cli/auth_nkey_command.go
This adds a new top level sub command "auth" that
will be used to add functionality found in "nsc".
As a first step this adds functionality matching the old "nk" command
=> Adds basic nk equivelant

README.md
Changing context name in example, since first is named "local" but then is referenced as "localhost". This might benefit new users of this CLI.
=> fix: changing context name in one command

cli/server_run_command.go
Eliminated duplicate (and incorrect) function to determine the per-user data directory based on `$XDG_DATA_HOME`.
Kept `dataParentDir()` function to maintain concept, but delegated to correct implementation `xdgShareHome()`.
=> Fix incorrect JetStream store dir when using $XDG_DATA_HOME #962.

cli/util.go
Resolves https://github.com/nats-io/natscli/issues/999
Before:
```
$ ./nats consumer pause
[localhost] ? Select a Stream stream
[localhost] ? Select a Consumer consumer
[localhost] ? Pause until (time or duration) 30s
[localhost] ? Really pause Consumer stream > consumer until 2024-03-02 17:32:51 Yes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xca3ff5]
goroutine 1 [running]:
github.com/nats-io/jsm%2ego.(*Consumer).StreamName(...)
/home/mavenir/Documents/opensource/natscli/vendor/github.com/nats-io/jsm.go/consumers.go:942
github.com/nats-io/jsm%2ego.(*Consumer).Pause(0x0, {0x0?, 0x0?, 0x1c28340?})
/home/mavenir/Documents/opensource/natscli/vendor/github.com/nats-io/jsm.go/consumers.go:907 +0x95 …
```
=> Ensure selectedConsumer by requesting ConsumerInfo, when calling selectConsumer

cli/sub_command.go
Fixes the sub command creating a JS context without taking all options (e.g. --js-domain
=> sub  command handling jsOpts

cli/server_mkpasswd_command.go
Fixed UI/UX for password encryption
1. The word 'Reenter' is creating confusion when encrypting a password, changed it to 'Re-enter'.
2. When Re-entered password does not match entered password, typed password is being exposed.
changed the error line to a user-friendly sentence.
=> password encryption UI/UX fix

cli/auth_nkey_command.go, cli/auth_xkey_test.go
=> adds xkey seal/open functionality to commandline

.github/workflows/release.yaml, archive/README.md, archive/archive_test.go, archive/reader.go, archive/tag.go, archive/tag_test.go, archive/writer.go, cli/audit_analyze_command.go, cli/audit_command.go, cli/audit_gather_command.go
Add new `audit` command, not fully baked, but useful to gather some initial feedback from users.
2 subcommands:
- `gather` pulls a number of artifacts from a cluster into a zip-file useful for debugging
- `analyze` runs a set of checks against a `gather` archive, highlighting potential problems (unhealthy servers, mismatching server versions, resources hitting capacity limits, ...)
-
=> Add (hidden) 'audit' command

.github/workflows/release.yaml, .goreleaser.yml
* Make release tag regex stricter (s/`.`/`\.`)
* Add missing build step
* Handle RC releases 
* Update Brew project homepage
=> Minor fixes and improvements to GH release workflow

cli/stream_command.go
This would create a SubjectTransformConfig with no subjects whenever s edit is called when previously no transforms were set
=> Prevent empty subject transform settings from being set

cli/sub_command.go
Adds the following flags to `nats sub`:
- `--subjects-only` only prints the subject for each message received
- `--timestamp` adds a time stamp of when the message is received
- `--delta-time` adds a time since the start of the command of when the message is received
=> Add flags to the `sub` command

README.md, cli/consumer_command.go, cli/server_check_command.go
Demonstrating a model that could be used to enable self-service monitoring for client assets
=> Metadata based monitoring for streams and consumers 

README.md
The last version of OS X went end of life several years ago. This updates the installation instructions to refer to the current Apple macOS.
=> Update installation instructions for macOS

cli/object_command.go
Using the nats cli, it was hard to tell whether or not a bucket was using a File storage or a Memory storage.
This commit introduces a row that displays the StorageType as reported from the ObjectBucketStatus structure
=> Report the storage type used in a `object info` command

cli/sub_command.go
Previously, report subjects only sorted by message count, but if two subjects had the same message count, they would not be sorted consistently.
This change sorts the subjects first by count, then by subject
=> Sort subjects consistently when doing nats subscribe --report-subjects

internal/audit/cluster_checks.go, internal/audit/server_checks.go
#1096 only checks for ` `, while other characters (e.g., `\n` in the server name can still break the cluster.
Signed-off-by: reubenninan <reuben@nats.io>
=> Fix whitespace check to include newlines

cli/bench_command.go
There is an issue with a Uiprogress runtime error during "nats bench" when the number of publishers exceeds the number of messages. This results in some publishers being assigned 0 messages, which is set as the total for the progress bar. However, Uiprogress does not accept zero as a valid total and throws a runtime error.
To prevent this error, the progress bar can be shown as already completed when there are no messages to publish.
Issue: https://github.com/nats-io/natscli/issues/1134
=> Fix progress bar display issue

cli/consumer_command.go
Update the `edit` action to use the loadConfigFile function instead of trying to do it itself. This allows us to edit with the output of `$ nats c info X Y --json > y.json` and flat, user defined configuration.
=> (#1136) Use loadConfigFile in edit action

cli/pub_command.go
Here we add the --jetstream flag to the publish action. This will publish messages via jetstream and process the ack message.
=> (#1130) Add --jetstream flag to publish

cli/consumer_command.go
Here we add the --interactive flag to the consumer edit action. This behaves the same as stream interactive edit.
=> (#1145) Support interactive edit for consumers

cli/audit_gather_command.go, cli/util.go
`doReqAsync` uses an adaptive timeout to stop listening for responses when the number of responses waited is zero.
In this PR:
- Create special value `waitFor=-1` to wait for the full `timeout` for responses
- Update `audit gather` wait for the full timeout
=> Allow turn off of doReqAsync adaptive timeout

cli/server_command.go, cli/server_consumer_check.go, cli/server_stream_check.go, internal/sysclient/healthstatus.go, internal/sysclient/sysclient.go, internal/util/util.go
Here we add the `stream-check` and `consumer-check` subcommands to the `server` command.
These subcommands are hidden, and will use the system credentials to iterate all servers, streams and consumers and display debugging related information to the user in a table.
=> (#1140) Add stream-check and consumer-check subcommands

cli/kv_command.go, cli/object_command.go, cli/util.go, options/options.go
Here we update both the kv and object commands to no longer use the deprecated nats.JetstreamContext and instead use jetstream.Jetstream.
We also fix some minor usability issues, like make the `revision` flag required for the `update` action, improve the error message when attempting to revert a key value in a bucket with history=1, and perform the revert with an `update` action instead of a `put`.
=> (maint) Update kv and object commands to use new jetstream api

cli/consumer_command.go, cli/server_graph_command.go, cli/stream_command.go, cli/util.go
Here we check if the value from Nats the we use to in the server, stream and consumer graph actions is > 0 before using it to calculate rate. This will prevent us from storing negative rates and breaking the graphs.
=> Improve rate calcuations for graphs

cli/stream_command.go
Previously there were too many columns for the headers, and `Active` was named incorrectly:
```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                Replication Report                                                │
├──────────────────┬────────┬──────────────┬──────────────────┬────────────────────────┬────────┬───────┬───────┬──┤
│ Stream           │ Kind   │ API Prefix   │ Source Stream    │ Filters and Transforms │ Active │ Lag   │ Error │  │
├──────────────────┼────────┼──────────────┼──────────────────┼────────────────────────┼────────┼───────┼───────┼──┤
│ stream           │ Mirror │ $JS.home.API │ source           │                        │        │ 528ms │ 0     │  │ …
```
=> Fix columns for mirrors under `Replication Report`

.github/workflows/release.yaml, .goreleaser.yml
Handle deprecated configuration settings, updating per guidance in <https://goreleaser.com/deprecations/>.
Add an internal `version:` field in the GoReleaser YAML, for v2.
Switch the GitHub Action to @v6 which will use goreleaser v2, and make the version explicitly `"~> v2"`.  Before, it said "latest" but that was implicitly bound by the action to be v1, leading to a little head-scratching.
=> goreleaser: switch to v2 config & GH Action

cli/bench_command.go
With the new changes to the max IPQ size on server v2.11 it is really easy to have some of the JS publish requests dropped when running nats bench using more than just a handfull of client connections.
This change just logs the error from a pub ack future and retries the publication instead of fatally stopping when this happens.
=> Bench command retry publication when pub ack future is an error

README.md
Fixes:
https://github.com/nats-io/nats.docs/issues/586
related server doc change:
https://github.com/nats-io/nats.docs/pull/782
server package was added in https://github.com/nats-io/nats-server/issues/2063 by scottf.
It lives here now:
https://github.com/ScoopInstaller/Main/blame/master/bucket/nats-server.json
Natscli config lives here and it is auto-updated by GitHub actions:
https://github.com/ScoopInstaller/Extras/blame/master/bucket/natscli.json
=> Update README.md: add windows instructions

.goreleaser.yml
Please, update the [fisk](github.com/choria-io/fisk) dependency version after https://github.com/choria-io/fisk/pull/54 merge.
[36f3fec](https://github.com/nats-io/natscli/commit/36f3fec3581a114f93fad3adb2f12b768d80f699) uses [zsh.complete.nats](https://github.com/ConnectEverything/client-tools/blob/main/zsh.complete.nats), but I consider that `generate_completions_from_executable` is more suitable for maintenance.
=> Add man page and zsh completion

cli/kv_command.go
As discussed in #1221 this change adds an `edit` command to update KV bucket's config.
Only the updatable properties are exposed as flags.
=> Add kv edit command

cli/server_check_command.go, cli/util.go, go.mod, go.sum, internal/exporter/exporter.go
Previously we handled jsm options correctly but in the move out of CLI we forgot to handle those at all meaning trace, domains, api prefix all stopped being supported.
This restores all that.
=> Enable domains and api prefixes in server check

cli/auth_account_command.go, go.sum, nats/auth_command_test.go
mappings has `add`, `rm`, `list` and `info` commands.
Add can take a --config flag pointing at a valid jwt, which it will then parse and extract the mappings from it.
=> (#1268) Add mappings action to auth command

cli/util.go
Since we use the prepare helper for account and system accounts, and those without jetstream, we really cant check this here
=> Reverts the availability check for js

cli/util.go, nats/main.go, options/options.go
This PR adds support for token-based authentication in the NATS CLI context options. It introduces a dedicated `Token` field to the `Options` struct, providing a clearer and more semantically correct way to handle token-based authentication compared to using the `Password` field.
- Added `Token` field to the `Options` struct
- Updated `loadContext` to support token-based authentication alongside existing username/password authentication
- Maintained backward compatibility with existing password-based authentication
Currently, token-based authentication requires using the `Password` field, which is semantically incorrect and can lead to confusion. This change provides a dedicated field for token authentication, making the code's intent clearer.
N/A
This change is backward compatible and …
=> Add token authentication support to context options

cli/account_command.go
#1322 broke the `nats account report connections` command. This should fix the regression.
=> Fix account report connections

cli/stream_command.go
Closes #1283 
Shows the 25 page size limit in helps, and also logs the limit when it is exceeded (both ideas are discussed in the issue)
=> UPDATED relevant help and logs about stream view page limit

cli/consumer_command.go
Closes #1084 .
The inner conditional statement is always true because  it's part of the outer conditional statement
=> Remove redundant condition in consumer command

cli/auth_nkey_command.go, cli/auth_xkey_test.go, nats/tests/auth_command_test.go, nats/tests/nats_nix_test.go, nats/tests/nats_test.go, nats/tests/nats_windows_test.go
The tests relied on `bash -c` to take in the commands from strings, as created by `fmt.Sprintf` statements throughout the code. This isn't available on Windows, the equivalent `cmd /c` does not support `""` or `''` quotes for arguments which would break a few of the tests. 
`exec.Command()` expects to take a slice and when provided with a slice of arguments the spaces do not matter - nor is there a need for `bash -c` or `cmd /c`. 
This PR provides the following:
* Converts all command arguments from strings to slices
* Fixes the timeout, it was not working as bash was spawning go and go the program. 
* Provides an implementation for *nix variants and Windows.
I have tested it on Windows, Linux and Mac. 
Note: For Windows you need `wc` from …
=> Cross platform testing & fix runNatsCli timeout

cli/object_command.go
Closes #1262 .
Edit for kv is already provided by another contribution. Inspired by that, here is the edit command for object store buckets.
Also there's a bonus commit here to sort the imports (they are already sorted in other files, so this one was probably missing).
=> Add object edit command

cli/kv_command.go, nats/tests/kv_test.go, nats/tests/nats_test.go
In the past if we edited a field, e.g. --ttl=5s, all the other values would be set to their default value.
We now create a copy of the bucket's config and only update the fields that the user explicitly specify.
=> Fix kv edit to not override unspecified fields

.goreleaser.yml
Per <https://goreleaser.com/deprecations/#archivesformat> the `archives.format` entry has been deprecated since GoReleaser v2.6.  It's now on 2.9.
Our GH Actions semver constraint is `~> 2`, so this should be a safe change for everyone except those with stale local installs of GoReleaser.
=> goreleaser: adapt to deprecated archives.format

cli/service_command.go, nats/tests/service_command_test.go
closes #1381 
Plaintext:
```shell
❯ ./nats service info WorkloadInspector --endpoint ENV       
Service Information
Service: WorkloadInspector (UuupEau8AYQIFumh5TaJqa)
Description: NATS micro service to inspect a NEX workload environment.
Version: 0.0.1
Endpoint Information:
Name: ENV
Subject: INSP.ENV
Queue Group: q
Metadata: request: 
Endpoint Statistics:
Requests: 6 in group "q"
Processing Time: 419µs (average 70µs)
Started: 2025-05-12 12:05:22 (53m28s ago)
Errors: 0
```
JSON:
```shell
❯ ./nats service info WorkloadInspector --endpoint ENV --json
{
"info": {
"name": "ENV",
"subject": "INSP.ENV",
"queue_group": "q",
"metadata": {
"request": ""
}
},
"stats": {
"name": "ENV",
"subject": "INSP.ENV",
"queue_group": "q",
"num_requests": 6,
"num_errors": 0,
"last_error": "", …
```
=> Add `--endpoint/-e` to `nats service info`

cli/sub_command.go, cli/util.go, nats/tests/sub_command_test.go
Here we update the sub action to use the modern jetstream package. As a side effect of this we now support both pull and push consumers with the --durable flag.
=> Rewrite sub to use nats.go/jetstream

cli/sub_command.go, nats/tests/sub_command_test.go
When we updated the sub command to use jetstream.jetstream, the output printed from direct gets regressed to the generic nats.Msg output style.
Here we revert the regression and update the tests to spot this in the future.
=> (maint) Fix direct get output

cli/stream_command.go
Just like missing consumers, show missing/inaccessible streams in `nats stream ls` and `nats stream report`.
=> Show missing streams in list/report

cli/server_check_command.go, go.mod, go.sum, internal/exporter/exporter.go
It naively checks anything with a printf style arguments and complains when passed only one argument, even if no alternative exist.
It also only support turning the check off for the entire codebase not just some lines, so we just have to play along
=> Align with the needs of go 1.24 go vet

cli/bench_command.go
Cleans up an un-needed log trace in nats bench js get
=> Cleanup bench log

cli/bench_command.go, internal/bench/constants.go, internal/bench/stats.go
Bench command now has its own modified and improved internal functionality for displaying and saving stats
Additional average latency stats added.
Rework bench js get.
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
=> Redo bench stats and bench js get

cli/columns.go, cli/consumer_command.go, cli/server_graph_command.go, cli/stream_command.go, cli/sub_command.go
The function that we use to format floats on graph axis 
https://github.com/dustin/go-humanize/blob/v1.0.1/comma.go#L84
drops decimal part. That creates Y-axis labels that are hard to read.
It also causes the position of the axis to readjust as you start at the graph.
In once console:
```
nats bench pub yo --msgs=100000000 --sleep 0.01s
```
In second console:
```
nats  sub 'yo' --graph
```
With this change, we always display decimal part, and it makes it easier to parse:
Also, drop number of decimal places to two, since that high precision is barely useful in cli graphs.
Fixes: https://github.com/nats-io/natscli/issues/1439
=> force number of decimal places on Y axis on graphs

cli/bench_command.go
When using R1 and not batch js publish bench's --create will create a stream with persistence mode = async (otherwise the stream gets created with persistence mode = default)
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
=> Adjust stream creation in nats bench
