- main.go
Initially submitted by @philpennock
> allow NATS_CONTEXT to set the context

- go.mod
- go.sum
- main.go
> Prepare release 0.0.20

- .goreleaser.yml
> create brew, rpm and deb packages

- .goreleaser.yml
> fix generated package names

- README.md
> mention releases and homebrew

- jsonschema.go
Just a minor bug I noticed while skimming over the code...
> Fix error formatting (missing a call to Sprintf)

- .goreleaser.yml
> add freebsd support to releases

- .goreleaser.yml
> also fix releasing new versions

- nats/stream_command.go
> byte parse the max message size value

- nats/context_command.go
- nats/util.go
> add context validation

- nats/nats_test.go
- nats/stream_command.go
> add tests for stream backups, fix timing issue

- nats/context_command.go
- nats/pub_command.go
> fix minor ux issues

- dependencies.md
- nats/nats_test.go
- nats/stream_command.go
> support --replicas for streams

- nats/pub_command.go
> support count and templates in request command

- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
> minor ux updates

- nats/stream_command.go
> improve zero time handling in stream state

- README.md
I have added the documentation about AUR package and also I have added the badge about available packages and their version.
> Add AUR Package

- go.mod
- go.sum
- nats/server_request_command.go
> support limiting requests by server tag

- go.mod
- go.sum
- nats/consumer_command.go
- nats/dev_command.go
- nats/main.go
- nats/stream_command.go
- nats/util.go
> initial work on validating dev proxy

- go.mod
- go.sum
- nats/account_command.go
- nats/dev_command.go
- nats/validating_proxy.go
> improve reporting account info errors, refactor proxy

- go.mod
- go.sum
> update dependencies for quorum events

- README.md
- nats/pub_command.go
- nats/reply_command.go
- nats/util.go
> support generating random strings

- go.mod
- go.sum
- nats/pub_command.go
- nats/reply_command.go
- nats/util.go
> improve template consistency

- go.mod
- go.sum
- nats/account_command.go
> extended account info

- nats/server_report_command.go
Signed-off-by: Benjamin Gilbert <bgilbert@backtick.net>
> Fix log message typo

- nats/account_command.go
> show connected cluster

- go.mod
- go.sum
- nats/consumer_command.go
- nats/stream_command.go
> support raft step down and leader election force

- go.mod
- nats/server_command.go
- nats/server_mkpasswd_command.go
- nats/server_raft_command.go
- nats/util.go
- nats/validating_proxy.go
> support creating nats server passwords

- nats/account_command.go
- nats/bench_command.go
- nats/cheat_command.go
- nats/context_command.go
- nats/events_command.go
- nats/latency_command.go
- nats/main.go
- nats/pub_command.go
- nats/reply_command.go
- nats/schema_command.go
- nats/server_command.go
- nats/sub_command.go
> add cheat command

- nats/pub_command.go
> fix cheat for pub command

- nats/server_command.go
- nats/server_report_command.go
> jsz report

- nats/context_command.go
- nats/util.go
> default survey selects to entries length capped to term height-4

- nats/cheat_command.go
- nats/server_command.go
> minor fix of cheat section list behavior

- nats/cheat_command.go
> also actually show cheats

- go.mod
- go.sum
- nats/nats_test.go
- nats/stream_command.go
> support new format snapshots

- nats/stream_command.go
> update stream report with cluster awareness

- nats/stream_command.go
> fix snapshot panic when stream is empty

- nats/pub_command.go
- nats/server_list_command.go
> show progress bar for publishing large numbers of messages

- nats/util.go
> fix detection of terminal size

- nats/server_list_command.go
- nats/server_ping_command.go
handle error statusses from server system account
> remove encoded connections

- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
> add initial consumer report

- go.mod
- go.sum
- nats/consumer_command.go
also ensure stream view messages are acknowledged
> humanize some more numbers in consumer report

- nats/stream_command.go
> improve report consistency

- nats/bench_command.go
- nats/pub_command.go
- nats/stream_command.go
- nats/util.go
> set progress width based on screen width

- go.mod
- go.sum
- nats/context_command.go
- nats/events_command.go
- nats/main.go
- nats/server_list_command.go
- nats/util.go
> add support for prefixes

- nats/util.go
> change peer sorting to alphabetical

- nats/consumer_command.go
> improve UX around Pull consumer creation and consumption

- go.mod
- go.sum
- nats/server_raft_command.go
> support meta leader step down placement

- go.mod
- go.sum
- nats/jsonschema_test.go
- nats/stream_command.go
> initial, basic, mirrors sources and syncs

- go.mod
- go.sum
- nats/nats_test.go
- nats/stream_command.go
> minor updates to mirror ux

- go.mod
- go.sum
- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
> support sources and mirrors

- .gitignore
- go.mod
- go.sum
- nats/consumer_command.go
> improve tracing

- go.mod
- go.sum
- nats/consumer_command.go
- nats/context_command.go
- nats/util.go
- nats/util_test.go
also fix Random(1024,1024) which would return
different length strings rather than always 1024
> fix various ux issues

- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
- nats/util_test.go
> expand stream report for replication

- nats/consumer_command.go
- nats/server_raft_command.go
- nats/stream_command.go
- nats/util.go
> minor ux tweaks

- go.mod
- go.sum
- nats/stream_command.go
> fix lost schema, show lost messages data

- dependencies.md
- go.mod
- go.sum
- nats/stream_command.go
> add dot graphs for stream report

- nats/stream_command.go
> remove panic in stream report without mirrors

- nats/stream_command.go
> update some stream ux

- go.mod
- go.sum
- nats/stream_command.go
> fix prompting for mirrors

- go.mod
- go.sum
- nats/consumer_command.go
> use a duration for expires

- nats/pub_command.go
- nats/stream_command.go
> allow interactive stream edits

- nats/server_raft_command.go
- nats/stream_command.go
> various small bug fixes

- nats/stream_command.go
> clarify the use of message id and message sequence

- nats/server_raft_command.go
> add some peer remove warnings

- nats/server_report_command.go
- nats/stream_command.go
this just guards against ">" when ack is on, but
realistically this is only marginally useful as
there are many other scenarios - use depending -
where a bad choice of subject can render the system
broken
> add basic subject validtion

- go.mod
- go.sum
- nats/stream_command.go
> initial support for cross account sources

- nats/stream_command.go
> small UX updates around sources and mirrors

- nats/server_check_command.go
- nats/server_command.go
> add a basic nagios protocol health check

- go.mod
- go.sum
- nats/consumer_command.go
- nats/nats_test.go
> add push consumer idle heartbeat support

- nats/server_report_command.go
> fix boolean for detecting online replicas

- nats/sub_command.go
> support subscribing to generated inboxes

- nats/sub_command.go
> add a short flag to nats sub --inbox

- go.mod
- go.sum
- nats/consumer_command.go
- nats/stream_command.go
> support flow control

- .github/workflows/test.yaml
- go.mod
- go.sum
> prepare for 0.0.22

- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
> support rendering leader distributions

- nats/consumer_command.go
- nats/nats_test.go
- nats/optional_boolean.go
> support optional booleans

- go.mod
- go.sum
- nats/consumer_command.go
> use UTC times to communicate with the API

- nats/consumer_command.go
- nats/nats_test.go
- nats/server_list_command.go
- nats/server_report_command.go
- nats/util.go
> support compacting hostnames removing common suffixes

- nats/nats_test.go
- nats/util.go
- nats/util_test.go
> fix a cluster rendering off by one

- go.mod
- go.sum
- nats/stream_command.go
> support filter subjects for stream view

- .github/workflows/test.yaml
- nats/server_check_command.go
- nats/server_check_command_test.go
> add additional features to server check

- go.mod
- go.sum
- nats/consumer_command.go
- nats/util.go
> improve consumer info performance

- nats/consumer_command.go
- nats/server_check_command.go
- nats/server_list_command.go
- nats/server_report_command.go
also fix report/list reverse order behavior
> add ability to check stream message counts

- nats/consumer_command.go
- nats/server_raft_command.go
> remove 1 consumer info call when removing a consumer

- go.mod
- go.sum
- nats/stream_command.go
> support num_deleted response in stream state

- nats/stream_command.go
> handle non JS reply subjects gracefully in stream view

- nats/stream_command.go
won't solve the purge stale problem for all cases, but
good for most, probably
> refresh info post purge

- nats/util.go
- nats/util_test.go
> handle peerless cluster info

- nats/util.go
> fix interpolation of ID in strings

- nats/server_info_command.go
> fix npe on non JS servers in server info

- nats/consumer_command.go
A quick fix to make the docs help people find the flag name
> Add --max-pending suggestion to help

- nats/main.go
- nats/traffic_command.go
hidden for the moment while we explore
> add a traffic monitor command

- nats/sub_command.go
- nats/util.go
> handle non terminal situations correctly

- go.mod
- go.sum
- nats/stream_command.go
> [added] support for domains in source/mirror interactive mode

- go.mod
- go.sum
- nats/server_request_command.go
> honor domain in server requests

- nats/server_info_command.go
- nats/server_raft_command.go
- nats/server_report_command.go
- nats/server_request_command.go
Also improve some system errors
> further support for domains

- nats/server_report_command.go
- nats/util.go
> improve error when a system account isnt used in jsz report

- go.mod
- go.sum
- nats/consumer_command.go
- nats/nats_test.go
> support max waiting

- nats/consumer_command.go
- nats/server_list_command.go
- nats/server_report_command.go
- nats/stream_command.go
- nats/traffic_command.go
- nats/util.go
> improve table visuals

- nats/server_report_command.go
When -j (json output) is provided server info will be included.
For accounts, we collect all server/cluster the account is present in.
```
> nats --context=sys server report connections 9
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                      1 Connections Overview                                                                       │
├──────┬──────────────────────────────┬──────────┬─────────────────┬───────────┬────────────────────────┬────────┬─────────┬──────────┬──────────┬───────────┬──────┤
│ CID  │ Name                         │ Server   │ Cluster …
```
> [added] display of server/cluster name to  server report cons/accounts

- nats/stream_command.go
> [added] ExternalStream to output of stream info

- nats/stream_command.go
> avoid npe accessing external sources in reports

- nats/server_check_command.go
- nats/server_check_command_test.go
> jetstream account monitoring

- go.mod
- go.sum
- nats/context_command.go
- nats/util.go
> support token auth via username

- nats/server_request_command.go
When host or name is given and no wait, set wait to 1
else if wait is 0 try to determine it
> use topology hints for server req

- nats/server_report_command.go
> drop debug messages

- nats/sub_command.go
> support dumping messages to file/stdout

- nats/stream_command.go
> support setting stream max consumers

- nats/governor_command.go
> add help to the gov sub command

- nats/server_list_command.go
> reverse sort clusters by connections

- nats/kv_command.go
> support cluster placement for kv

- nats/kv_command.go
> support deleting a key

- go.mod
- go.sum
- nats/kv_command.go
- nats/kv_command_test.go
- nats/nats_test.go
> support non destructive deletes and watch ops

- go.mod
- go.sum
- nats/kv_command.go
> show additional bucket limit values

- go.mod
- go.sum
- nats/kv_command.go
- nats/kv_command_test.go
- nats/util.go
> use bytes based api, handle non printable data

- go.mod
- go.sum
- nats/governor_command.go
> use recently added gov helpers

- go.mod
- go.sum
- nats/governor_command.go
- nats/kv_command.go
- nats/kv_command_test.go
> updates for latest kv adr

- nats/kv_command.go
- nats/server_command.go
> avoid creating new buckets when reading

- nats/util.go
> comply with latest header design ADR

- nats/consumer_command.go
- nats/server_report_command.go
> improve handling of large number of connections

- nats/stream_command.go
> support getting last message per subject from a stream

- nats/stream_command.go
> also prompt for a last subject if no id given

- nats/account_command.go
- nats/server_report_command.go
> support account report connz

- nats/server_report_command.go
> render short ids correctly

- nats/server_report_command.go
> show 12 character short ids

- nats/account_command.go
- nats/server_report_command.go
- nats/server_request_command.go
Also print connection kind hints
> suport sbject filters in req connz and report connz

- README.md
Updated the readme file as it had now outdated nats bench examples
> Update readme with new nats bench examples

- go.mod
- nats/util.go
> support snappy compression on server reqs

- nats/server_check_command.go
> ensure check outfile is readable

- go.mod
- nats/consumer_command.go
> basic fc for consumer sub

- nats/consumer_command.go
- nats/server_check_command.go
> show reply subject when failing in consumer sub

- nats/consumer_command.go
- nats/sub_command.go
> handle fc and stalled fc better

- nats/server_report_command.go
- nats/sub_command.go
> Improve account report user experience

- nats/server_report_command.go
> when rendering connections, report servers and clusters

- nats/main.go
> ensure usage output goes to stdout for easy paging etc

- nats/server_list_command.go
> support sorting server list by name

- nats/consumer_command.go
- nats/server_list_command.go
> do not show queue group in pull

- nats/stream_command.go
> set dupe window to max age when max age is less than 2 minutes

- nats/bench_command.go
Also remove --no-queue which was only for --reply since it doesn't make sense in typical request/reply use cases to do not have repliers in a queue group (as it would lead to duplicate processing) why offer it as a kind of benchmark.
> Improve logging and progress bar

- go.mod
- go.sum
- nats/server_list_command.go
- nats/util.go
> improve server list logic around number of expected nodes

- go.mod
- go.sum
- nats/nats_test.go
- nats/stream_command.go
> support sealing streams

- go.mod
- go.sum
- nats/kv_command.go
- nats/kv_command_test.go
> Update for KV design changes related to purge being key orientated

- nats/server_list_command.go
> minor ux updates in server list

- nats/nats_test.go
- nats/stream_command.go
> support stream permissions

- nats/kv_command.go
- nats/object_command.go
- nats/util.go
* Progress bars
* File replace protection
* Bucket into display
* Object info display improvements
> various obj command refinements

- nats/object_command.go
Also improve header rendering and dont show id
> allow storage kind to be picked for obj

- nats/stream_command.go
> hide system streams in stream ls unless -a

- nats/kv_command.go
- nats/object_command.go
> add kv and obj list commands

- nats/stream_command.go
> modernise stream ls

- nats/kv_command.go
- nats/object_command.go
- nats/stream_command.go
> include last-used information in various ls outputs

- nats/server_command.go
- nats/server_run.go
> poc nats server run command

- go.mod
- go.sum
- nats/consumer_command.go
- nats/stream_command.go
- nats/util.go
> filter out internal streams from stream selections by default

- nats/context_command.go
- nats/server_run.go
> updates for local development instance

- nats/server_run.go
> pick a random port, detect in-use contexts

- nats/server_run.go
> ensure contexts are removed after stop not before start

- nats/consumer_command.go
> correctly handle deliver group in all cases

- nats/server_configure_command.go
> remove accidentally added files

- nats/consumer_command.go
- nats/nats_test.go
> support editing consumers

- cli/account_command.go
- cli/backup_command.go
- cli/bench_command.go
- cli/cheat_command.go
- cli/cli.go
- cli/consumer_command.go
- cli/context_command.go
- cli/errors_command.go
- cli/events_command.go
- cli/governor_command.go
- cli/kv_command.go
- cli/latency_command.go
- cli/object_command.go
- cli/pub_command.go
- cli/reply_command.go
- cli/restore_command.go
- cli/rtt_command.go
- cli/schema_command.go
- cli/server_command.go
- cli/server_ping_command.go
- cli/server_run_command.go
- cli/stream_command.go
- cli/sub_command.go
- cli/traffic_command.go
- cli/util.go
- nats/main.go
> further improvements to embedable mode

- cli/consumer_command.go
- cli/governor_command.go
- cli/latency_command.go
- cli/rtt_command.go
- cli/server_check_command.go
- cli/sub_command.go
- cli/util.go
> use the configured nats conn for inbox generation

- nats/main.go
> sets a dynamic version string for installs using go install

- cli/context_command.go
> handle context load errors when producing list table

- cli/kv_command.go
- cli/stream_command.go
Also remove unwanted debug lines
> ensure kv add API interactions are traced

- LOCAL_DEVELOPMENT.md
- cli/server_run_command.go
> set a local domain when extending another network

- cli/consumer_command.go
> avoid overflowing consumer pending percentage

- cli/pub_command.go
Signed-off-by: Byron Ruth <b@devel.io>
> Add support for the sleep duration in requests

- cli/bench_command.go
Small improvements to stream definition/usage allowing for usage of an externally defined stream, automated max ack pending setting
> Small improvements to jetstream mode

- cli/kv_command.go
> combine the kv rm and kv del commands

- cli/consumer_command.go
- go.mod
- go.sum
- nats/nats_test.go
> support consumer backoffs

- cli/stream_command.go
> fix listing stream names only

- cli/consumer_command.go
- cli/stream_command.go
> add stream and consumer cheats

- install.ps1
This is a modified version of install.ps1 found here https://github.com/ConnectEverything/client-tools/pull/2
It's modified to only install the cli, either the stable or nightly. It's been discussed about adding the ability to install a specific release tag.
> powershell installer

- cli/pub_command.go
- cli/schema_info_command.go
- cli/stream_command.go
- cli/sub_command.go
- go.mod
- go.sum
> various small ux updates

- cli/sub_command.go
> allow "nats sub" to subscribe to jetstream streams

- cli/sub_command.go
> update help output

- cli/stream_command.go
> wording tweaks for max stream size question

- cli/kv_command.go
add checking and updating of discard policy during `kv upgrade <bucket>`
> kv upgrade discard policy

- cli/stream_command.go
> remove some problem flags from stream edit

- cli/bench_command.go
> validate --storage value in bench

- cli/kv_command.go
- cli/stream_command.go
* Correct formatting in kv info
* Detect and warn more cases for the upgrade prompt
* Rename --tags to --tag in stream add
> UX fixes for KV and Stream

- cli/stream_command.go
It is typical to do "nats s info --json" and then using that
with "nats s add --config" to create a new stream, but this
was not possible because config is nested in info, forcing
people to use jq tricks.
We now detect if its a info file and do the tricks for
users
> support adding stream from a info json

- cli/util.go
- go.mod
- go.sum
Signed-off-by: Waldemar Quevedo <wally@nats.io>
> Update nats client trace usage to latest nats.go

- cli/util.go
> consistent tracing output between cli and jsm

- cli/context_command.go
> adds a ctx copy command

- cli/kv_command.go
- cli/object_command.go
- cli/stream_command.go
- go.mod
- go.sum
> show full cluster info for kv/obj

- cli/bench_command.go
> synchronise bench publisher startup

- cli/kv_command.go
- cli/object_command.go
Better consistency with stream and consumer info
> Update UX for kv and obj info

- cli/account_command.go
- cli/server_check_command_test.go
- go.mod
- go.sum
> Fixes for 2.8.0 compatability

- cli/stream_command.go
- cli/util.go
> avoid extra blank line in names lists

- cli/consumer_command.go
- cli/stream_command.go
Also avoid some non name output in stream ls
> add --names for consumer list

- cli/stream_command.go
Viewing them will either not work or remove WQ
entries
> preview viewing WQ streams

- cli/consumer_command.go
> minor consumer info UX update

- cli/stream_command.go
> support editing stream placement

- cli/stream_command.go
> improve rendering of alternates

- cli/account_command.go
- cli/stream_command.go
> add a account backup command to backup all streams

- go.mod
- go.sum
> update dependencies for 2.8.0 compat

- cli/account_command.go
- cli/stream_command.go
- cli/util.go
- go.mod
- go.sum
> require stream size when max_bytes_required is set

- cli/stream_command.go
- cli/util.go
> improve error when max bytes is required

- cli/pub_command.go
> fix nats pub that behaved like nats req

- cli/stream_command.go
> allow placement to be adjusted on restore

- cli/object_command.go
- go.mod
- go.sum
> Release 0.0.32

- cli/account_command.go
account restore is for convenience and after error checking,
calls stream restore, for each stream.
> [add] account restore to match account backup

- cli/stream_command.go
> take name from config if not supplied

- cli/pub_command.go
- cli/util.go
> fix request progress bar handling

- cli/consumer_command.go
- nats/nats_test.go
> ensure max deliver is settable to -1 with backoff none

- cli/consumer_command.go
- go.mod
- go.sum
> support MaxRequestMaxBytes for consumers, do not prompt interactively

- cli/consumer_command.go
- go.mod
- go.sum
> support custom replica and memory consumers

- cli/stream_command.go
- go.mod
- go.sum
> support stream repub

- cli/consumer_command.go
- cli/stream_command.go
> remove some redundant boolean invert help hints

- cli/stream_command.go
Add the number of subjects to the info command.
WDYT to add to report?
> Add stream number of subject info

- cli/backup_command.go
- cli/pub_command.go
- cli/restore_command.go
Also fix a bug with printing raw replies in nats req
> deprecate the nats backup and nats restore commands

- cli/pub_command.go
- cli/stream_command.go
Also fix progress printing multi requests
> Timeout backups after 5 seconds

- cli/bench_command.go
Note, also fixes trying to define the consumers when a consumer name is explicitly passed as an argument
> Fixes nats bench multisubject option for batch publications

- cli/stream_command.go
- go.mod
- go.sum
- nats/nats_test.go
> support allow direct on streams

- cli/stream_command.go
> fix bug in go time format strings

- cli/account_command.go
- go.mod
- go.sum
> render TLS connection info in account info

- cli/consumer_command.go
> Support deliver group for consumer sub

- go.mod
- go.sum
- nats/main.go
> show improved error for missing flags, arguments and commands

- cli/sub_command.go
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
> Allow using a durable consumer

- cli/sub_command.go
- go.mod
- go.sum
> support binding to a specific stream in nats sub

- cli/util.go
> only load json files as context files

- cli/server_run_command.go
- fix lines indentation 
- trim white spaces 
Signed-off-by: Daniel Joudat <danieljoudat@gmail.com>
> fix template

- GOVERNANCE.md
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
> Update GOVERNANCE.md for NATS CLI

- cli/stream_command.go
> fix inversion of logic in allow delete and allow purge

- cli/consumer_command.go
- cli/stream_command.go
> render various numbers with commas

- cli/stream_command.go
> fix retrying waiting for a leader on stream leader evict

- cli/kv_command.go
> support republish options for kv add

- cli/account_command.go
> sort tiers when rendering account info

- cli/kv_command.go
- go.mod
- go.sum
> remove KV experimental warning

- cli/sub_command.go
We now load the stream to get its subjects and use that in the
displayed help rather than empty string for subject
> render stream subjects when binding to a stream

- cli/stream_command.go
> improve UX when asking source filter subject

- cli/sub_command.go
> log when matching replies

- cli/stream_command.go
- go.mod
- go.sum
> update str subjects to show message counts

- cli/stream_command.go
> improve nats s subjects

- cli/server_request_command.go
> support requesting healthz from servers

- cli/server_report_command.go
- go.mod
- go.sum
> support showing server id for the js leader

- cli/stream_command.go
- go.mod
- go.sum
> support discard new on a per subject basis

- cli/server_list_command.go
> render cores in server list and optimise the table size

- cli/pub_command.go
- cli/reply_command.go
- cli/util.go
> export request payload as .Request

- cli/server_report_command.go
- cli/util.go
> improve error handling in connections report

- cli/stream_command.go
> do not offer stream retention as an edit option

- cli/account_command.go
- cli/kv_command.go
- cli/object_command.go
- cli/stream_command.go
- go.mod
- go.sum
> add stream subject filters to list and report

- cli/stream_command.go
- cli/sub_command.go
> clarify some help text for durations

- cli/consumer_command.go
> default to all start policy for consumers

- cli/stream_command.go
> remove unused variables

- cli/server_request_command.go
> fix nil pointer issue when constructing server filters

- cli/reply_command.go
> support parsing command bodies using standard templates

- cli/stream_command.go
Also --state on stream info to achieve the same
> add a stream state command that shows only state

- cli/stream_command.go
> support mirror direct

- cli/consumer_command.go
- cli/stream_command.go
> remove some warnings when -f is used

- cli/cli.go
- cli/server_check_command.go
> Allow the namespace used by prometheus to be configured

- cli/server_check_command.go
> support cli override for the namespace

- cli/server_check_command.go
Looks for stream messages on a specific subject
and assert their age or content
> add "server check msg" command

- cli/server_report_command.go
> include the client port in connections report

- nats/main.go
> support not loading any contexts with --no-context

- cli/account_command.go
- cli/consumer_command.go
- cli/kv_command.go
- cli/object_command.go
- cli/server_check_command.go
- cli/stream_command.go
- go.mod
- go.sum
Also fix rendering of subjects list
> render "missing" data for consumers and streams

- cli/stream_command.go
> allow additional overrides when loading from file

- cli/server_request_command.go
> Add a subject filter to server req subsz

- cli/server_request_command.go
> Improve help layout using better placeholders

- cli/consumer_command.go
- cli/stream_command.go
- nats/nats_test.go
> allow most prompts to be skipped in c and s add with --defaults

- cli/consumer_command.go
- cli/server_report_command.go
- cli/stream_command.go
> logic fix for accepting defaults

- cli/server_check_command.go
- cli/server_check_command_test.go
> support checking message timestamp based on body

- cli/micro_command.go
- cli/util.go
- go.mod
- go.sum
> add basic micro command

- cli/micro_command.go
> ensure correct service id is accessed in micro info

- cli/consumer_command.go
Allows you to terminate a message
> Adds '--term' to 'consumer next'

- cli/account_command.go
- nats/main.go
> Ensure consumer backups can be opted out of

- cli/server_report_command.go
> report when the cluster is in an impossible leader situation

- cli/server_check_command.go
Also ensure prom namespace is used for the status metric
> fix prometheus status_code metric that was always 0

- cli/micro_command.go
- cli/server_request_command.go
- go.mod
- go.sum
> updates for multi endpoint micro services

- cli/stream_command.go
* remove a duplicated nil-handling block
* ~~document why we need to use a sentinel~~
* ~~document that we chose 'none' as our sentinel~~
* use fooSet variables to distinguish between "set by user to empty string" and "not set at all"
* use an empty cluster or a single empty tag to remove those constraints
~~This does mean that if someone creates a cluster called `none` or uses `none` as a tag, then they're out of luck with these flags.  We can pick another sentinel value if we think that's a blocker, I'm not invested in `none`, it simply seemed the least bad way out.~~
> stream edit: support removing Placement constraints

- cli/schema_validate_command.go
> support reading data from stdin for validation

- cli/micro_command.go
- cli/pub_command.go
- cli/schema_command.go
- cli/schema_req_command.go
- cli/schema_validate_command.go
- go.mod
- go.sum
> adds a schema req command to validate network services

- cli/server_check_command.go
- cli/server_check_command_test.go
- monitor/monitor.go
- monitor/perfdata.go
- monitor/result.go
> extract the monitor rendering code in a reusable package

- cli/stream_command.go
- go.mod
- go.sum
- monitor/result.go
> invert replicas find, also bug fix in checks

- cli/consumer_command.go
- cli/stream_command.go
- cli/util.go
- go.mod
- go.sum
> support stream and consumer metadata

- cli/account_command.go
> report the server version in account info

- cli/server_report_command.go
> scope report jsz to a specific account when requested

- .github/workflows/test.yaml
- cli/cli.go
- cli/server_report_command.go
- cli/util.go
- nats/nats_test.go
This is causing JSON-rendered output to be invalid.
Signed-off-by: Byron Ruth <byron@nats.io>
> Remove spurious print statement

- cli/server_account_command.go
- cli/server_command.go
- cli/server_list_command.go
- cli/util.go
> adds a new "server account info" command

- cli/server_account_command.go
> minor ux updates for server account info

- cli/context_command.go
> support editing corrupt contexts

- cli/kv_command.go
- cli/util.go
Also shows the context name in prompts when --context is passed
> adjust prompts on ctx config

- cli/sub_command.go
This was motivated by wanting to write a script without blocking indefinitely.
Of course, feel free suggest an alternative approach or reject.
> Add support for sub --wait and bind to existing durable

- cli/micro_command.go
- go.mod
- go.sum
> improve micro info ux 

- cli/util.go
- go.mod
- go.sum
Also prevents selecting unknown contexts
> avoid panic on unknown selected contexts

- cli/stream_command.go
This adds support to the NATS CLI for configuring stream compression. 
Depends: nats-io/nats-server#4072, nats-io/jsm.go#445
Signed-off-by: Neil Twigg <neil@nats.io>
> Support for stream compression

- cli/context_command.go
This was undone when the yaml editing mode was added
> Restore corrupt context handling

- cli/stream_command.go
- go.mod
- go.sum
Signed-off-by: Neil Twigg <neil@nats.io>
> Show stream compression only if compressed, regardless of store type

- cli/kv_command.go
Just a small change, merged identical switch cases checking the operation type in the watch action.
> Merge identical switch cases

- cli/stream_command.go
Implements multi-filter sources and mirrors in stream_command.go
(needs nats-server with this PR https://github.com/nats-io/nats-server/pull/4403 to display info properly)
> Implements multi-filter sources and mirrors

- cli/server_report_command.go
Previously we would gather all connz responses and then filter them after flattening them.
This works fine but with 100s of thousands of responses a 4GB machine quickly runs out of memory
We now do filter parsing right after getting each connz response so each response is filtered before being stored, thus we shrink the total data set as its gathered and we only ever filter a single server response at a time
> Adjust when connz responses are filtered

- README.md
Add how to install from the shell in one line to the README
> Add how to install from the shell in one line

- cli/auth_account_command.go
- cli/auth_command.go
- cli/auth_nkey_command.go
- cli/auth_operator_command.go
- cli/auth_user_command.go
- cli/columns.go
- cli/server_command.go
- cli/server_run_command.go
- cli/server_watch_command.go
- cli/util.go
Adds initial ability to watch account activity based on server advisories
> Adds new server watch command

- cli/server_report_command.go
- cli/server_request_command.go
Streamlines things a bit on big and busy networks
> Default to open not all for connections

- cli/kv_command.go
- nats/kv_test.go
- nats/nats_test.go
Check if we want an empty value or read from StdIn.
Added test for **kv create** and **kv update**
> [ADD] KV check if we need to read from stdin

- cli/consumer_command.go
> feat: make inactive-threshold available for con edit command

- cli/auth_account_command.go
- cli/auth_command.go
- cli/auth_nkey_command.go
- cli/auth_operator_command.go
- cli/auth_user_command.go
- cli/config.go
- cli/consumer_command.go
- cli/context_command.go
- cli/rtt_command.go
- cli/schema_search_command.go
- cli/schema_validate_command.go
- cli/server_account_command.go
- cli/server_list_command.go
- cli/server_report_command.go
- cli/server_run_command.go
- cli/service_command.go
- cli/stream_command.go
- cli/sub_command.go
- cli/util.go
- cli/util_test.go
- columns/columns.go
- go.sum
- internal/auth/auth.go
- internal/util/util.go
Bit of a long slog as much depends on opts which lives in cli that will have to move to really finish this but its a start
> Start clearing out unanchored funcs from cli package

- cli/consumer_command.go
- cli/server_cluster_command.go
- cli/stream_command.go
Add the force option to ignore the current leader for:
- cluster
- stream
- consumer
> [ADD] step-down force option

- cli/sub_command.go
> Fix typo in help output

- cli/sub_command.go
commit df25097dab9e2ecf707165f365ebd0e7a9619518
Author: roeschter <michael@roeschter.de>
Date:   Thu Jun 20 11:31:24 2024 +0200
Spelling
commit fd7f34597dc16742213e4cdf5630737cd4c5367e
Merge: 8c05be7 3a7c770
Author: roeschter <michael@roeschter.de>
Date:   Wed Jun 19 13:30:40 2024 +0200
Merge branch 'main' into sub-pull-durable-docs
commit 8c05be7dcf3a65f53e379758f90f114538198290
Author: roeschter <michael@roeschter.de>
Date:   Wed Jun 19 13:27:50 2024 +0200
Formatting and one more JS example
commit e527b1f71549184765f24aa82664fde7e6fd7a40
Author: roeschter <michael@roeschter.de>
Date:   Mon Jun 17 20:36:52 2024 +0200
Updated help
Will implement better support for WorkQueue later. With proper warning and overrides.
> Squashed commit of the following:

- cli/bench_command.go
- cli/cheats/bench.md
Many changes, improvements and new features, including: completely different arguments and flags, using the new service framework and the new JS API.
> New version of the bench command

- internal/audit/checks.go
- internal/audit/cluster_checks.go
- internal/audit/server_checks.go
Signed-off-by: reubenninan <reuben@nats.io>
> Add whitespace checks to audit analyze

- cli/server_report_command.go
But really the entire function should be rewritten around what is in jsm.go/connbalancer
> fix connz paging

- internal/scaffold/scaffold.go
Resolves https://github.com/nats-io/natscli/issues/1153
> Fix server generate on windows when using fs paths

- cli/server_consumer_check.go
- cli/server_report_command.go
- cli/server_stream_check.go
- cli/server_watch_js_command.go
- go.mod
- go.sum
> Support rendering API Pending in various places

- cli/audit_analyze_command.go
- cli/audit_checks_command.go
- cli/audit_command.go
- cli/audit_gather_command.go
- internal/audit/account_checks.go
- internal/audit/checks.go
- internal/audit/cluster_checks.go
- internal/audit/leafnode_checks.go
- internal/audit/metacluster_checks.go
- internal/audit/server_checks.go
- internal/audit/stream_checks.go
Also adds a command to list known plugins.
Prepare to allow check config to be supplied on the cli.
> Turn audit checks into plugins

- cli/stream_command.go
- go.mod
- go.sum
We set a default of 15m to avoid the server behavior of changing the already deployed streams later should the default change
Also warn if KV buckets are being interacted with by the stream command, do not override that with --force
> Support subject delete markers

- cli/stream_command.go
In the past when a user ran `stream edit` without the `--compression` flag, the empty flag would get parsed as the compression type `none`. This means that if compression was set to `s2`, every edit without the flag would look like there was a change to the stream's compression.
In this commit we remove the default value of the compression flag, and only change the configuration if the value has been explicitly set.
> (#12633) Fix edit when not passing --compression flag

- cli/bench_command.go
Fixes and improves the bench command for specifying timeouts
> Fix and improve the bench command for specifying timeouts

- cli/bench_command.go
for: `bench pub`, `bench js pub` and `bench service request`: Adds the ability to read the message payload from a file with the `--payload` flag and to set headers on the message with `--header`.
> Add payload and header flags for bench command

- cli/server_report_command.go
Here we add a --watch x flag to the server report action. When called with this flag execution will not terminate and instead refresh the results every x seconds.
> Add --watch flag to server report action

- cli/bench_command.go
- Adds `--filter` flag to `nats bench js consume` and `nats bench js fetch` commands
- Allows filtering JetStream messages by subjects during benchmarking
- Maintains consistency with existing `--filter` flag in consumer commands
- Added `filterSubjects []string` field to `benchCmd` struct
- Added flag definition using `StringsVar` pattern in `addJSConsumerFlags`
- Updated `createOrUpdateConsumer` to include `FilterSubjects` in consumer config
- Added filter display to benchmark banner output
> Add --filter flag to bench js consume and fetch commands

- cli/pub_command.go
- nats/tests/pub_command_test.go
As we use the nats cli to publish stdout to a message bus we have come across cases where normal data is being interpreted and generally the template processing will fail. 
This flag allows a user to specify `--no-templates` to bypass template processing in the subject and body of a published message.
> Implement --templates flag to disable template processing on publish

- cli/bench_command.go
Add async error handler
Minor improvements (benchCmd has only pointer receivers) and fix typo
> Add a connection async error handler

- cli/server_consumer_check.go
- cli/server_stream_check.go
Documented where STDIN is coming from. Also updated cheat sheet.
> Documentation

- cli/bench_command.go
Adds a new `js get` bench command that uses batched direct gets to retrieve the messages from the stream
Adds the client number to the log printouts in bench
Adds --filter to bench js ordered
> Batched direct gets in `nats bench`

- cli/bench_command.go
Implements bench js pub using batching
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
> Implements bench js pub using batching

- cli/kv_command.go
- go.mod
- nats/tests/kv_test.go
- nats/tests/server_command_test.go
Also move tests to new JetStream package
> Support metadata in KV

- cli/sub_command.go
Basic sub only allowed one subject with a queue group, now does multiple Graph and Report Subjects did not support queue groups
> Fix queue groups for sub, graph and report subjects

- cli/object_command.go
A slack user noticed this was missing.
> Add chunk-size option for object put
